version: '1.0'

services:
  backend:
    image: ghcr.io/rdvhoorn/mlopsshowcase/backend:latest
    ports:
      - "9000:9000"
    environment:
      - MODEL_PATH=/app/models/best_model.pkl
      - HOST=0.0.0.0
      - PORT=9000
      - LOG_LEVEL=INFO
    networks:
      - iris-network
    volumes:
      - ./backend/models:/app/models

  frontend:
    image: ghcr.io/rdvhoorn/mlopsshowcase/frontend:latest
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - iris-network
    environment:
      - BACKEND_URL=http://backend:9000
      - METRICS_PATH=metrics.json
      - LOG_LEVEL=INFO
      - STREAMLIT_SERVER_PORT=80
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
    volumes:
      - ./frontend/metrics.json:/app/metrics.json

networks:
  iris-network:
    driver: bridge 