name: Update Local Server After Image Push

on:
  workflow_run:
    workflows: ["Build and Push Frontend Docker Image", "Build and Push Backend Docker Image"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: self-hosted

    steps:
      - name: Pull newest images
        run: |
          docker compose pull

      - name: Recreate running services
        run: |
          cd server
          docker compose up -d --no-deps --build backend
          docker compose up -d --no-deps --build frontend